version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"    # AMQP protocol port
      - "15672:15672"  # Management UI port 
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - redis
      - rabbitmq

  analyzer:
    build: .
    command: npm run analyze
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - rabbitmq
